#!/bin/bash
#SBATCH --account=def-panos
#SBATCH --gres=gpu:1 
#SBATCH --cpus-per-task=2
#SBATCH --mem-per-cpu=8G
#SBATCH --time=00:50:00
#SBATCH --mail-user=nca3@sfu.ca
#SBATCH --mail-type=ALL

module load python/3.6
module load nixpkgs/16.09  intel/2018.3  cuda/10.1 cudnn/7.6.5
module load gcc/7.3.0 opencv/4.2.0 arch/avx512 StdEnv/2018.3

export LD_LIBRARY_PATH=${LD_LIBRARY_PATH}:${CUDA_HOME}/lib64:/cvmfs/soft.computecanada.ca/easybuild/software/2017/CUDA/cuda10.1/cudnn/7.6.5/lib64/

echo "Job start at $(date)"

nvidia-smi

SOURCEDIR=$(pwd)
echo "source directory: $SOURCEDIR"

#source /home/$USER/env_fastsrgan/bin/activate
#pip install --no-index tensorflow_gpu==2.2.0 opencv_python_headless==4.1.1.26 numpy
# Prepare virtualenv
virtualenv --no-download $SLURM_TMPDIR/env
source $SLURM_TMPDIR/env/bin/activate
# Prepare virtualenv
pip install --no-index -r $SOURCEDIR/requirements.txt

#cd /home/$USER/scratch/Fast-SRGAN-ITMO
echo $PWD
echo "Inference..."
python infer.py --image_dir images --output_dir outputs \
--gen "models/generator.h5"
